# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_noise_filter.ipynb.

# %% ../nbs/10_noise_filter.ipynb 2
#| eval: false
from __future__ import annotations
import pandas as pd
import numpy as np
from tqdm import tqdm
from jaxtyping import *
from typing import *
import torch as t
import torch.nn.functional as F
import matplotlib.pyplot as plt
import seaborn as sns
import gc
import transformer_lens as tl
import peft
import transformers as tr

# %% auto 0
__all__ = ['format', 'to_str_tokens', 'hooks', 'easy_generate', 'easy_forward', 'to_chat_fn', 'get_contrastive_steering_vectors',
           'test_steering_vectors']

# %% ../nbs/10_noise_filter.ipynb 6
def format(prompt: str | list[str], template: str="{prompt}") -> list[str]:
    if isinstance(prompt, str):
        prompt = [prompt]
    return [template.format(prompt=p) for p in prompt]

# %% ../nbs/10_noise_filter.ipynb 7
def to_str_tokens(tokenizer: tr.AutoTokenizer, prompt: str | list[str]) -> str:
    if isinstance(prompt, str):
        prompt = [prompt]
    return [tokenizer.decode(i) for p in prompt for i in tokenizer.encode(p, add_special_tokens=False)]

# %% ../nbs/10_noise_filter.ipynb 8
class hooks():
    def __init__(self, model, hooks: list[tuple[t.nn.Module, Literal['pre', 'post'], callable]]):
        """
        Args:
            model: The model to hook
            hooks: A list of tuples of the form (module, hook_type, hook_fn)
                module: The module to hook
                hook_type: The type of hook to register ('pre' or 'post')
                hook_fn: The function to call when the hook is triggered.
                    For 'pre' hooks: takes the first input tensor and returns modified tensor.
                    For 'post' hooks: takes the first output tensor (hidden states) and returns modified tensor.
                    The hook automatically handles tuple unpacking/repacking for transformer layers.
        """
        self.model = model
        self.handles = []
        self.hooks = hooks

    def __enter__(self):
        for module, hook_type, hook_fn in self.hooks:
            # Use default argument to capture hook_fn by value, not by reference
            # (avoids classic Python closure-in-loop bug)
            def post_hook(m, input, output, fn=hook_fn):
                # Handle tuple outputs (common in transformer layers which return (hidden_states, ...))
                if isinstance(output, tuple):
                    modified_first = fn(output[0])
                    return (modified_first,) + output[1:]
                else:
                    return fn(output)

            def pre_hook(m, input, fn=hook_fn):
                if not isinstance(input, tuple): raise ValueError(f"input is not a tuple, it is {type(input)}")
                modified_input = fn(input[0])
                return (modified_input,) + input[1:]

            if hook_type == 'pre':
                self.handles.append(module.register_forward_pre_hook(pre_hook))
            elif hook_type == 'post':
                self.handles.append(module.register_forward_hook(post_hook))
            else:
                raise ValueError(f"Invalid hook type: {hook_type}")

    def __exit__(self, type, value, traceback):
        for handle in self.handles:
            handle.remove()

# %% ../nbs/10_noise_filter.ipynb 9
def easy_generate(model, tokenizer, prompts: list[str], **kwargs):
    """
    Args:
        model: The model to generate from
        prompts: A list of prompts to generate from
        **kwargs: Additional keyword arguments to pass to the model.generate method
    """
    inputs = tokenizer(prompts, return_tensors='pt', padding=True, padding_side='left').to(model.device)
    generations = model.generate(**inputs, **kwargs)
    return tokenizer.batch_decode(generations, skip_special_tokens=True)

# %% ../nbs/10_noise_filter.ipynb 12
def easy_forward(model, tokenizer, prompts: list[str], **kwargs):
    tokens = tokenizer(prompts, return_tensors='pt', padding=True).to(model.device)
    return model(**tokens, **kwargs)

# %% ../nbs/10_noise_filter.ipynb 13
def to_chat_fn(tokenizer, system_prompt: str="You are a helpful assistant.", no_system_prompt: bool=False):
    def to_chat(prompts: list[str], system_prompt: str=system_prompt, **apply_chat_kwargs):
        if isinstance(prompts, str):
            prompts = [prompts]
        
        if no_system_prompt:
            convs = [[dict(role="user", content=p)] for p in prompts]
        else:
            convs = [[dict(role="system", content=system_prompt), dict(role="user", content=p)] for p in prompts]

        if apply_chat_kwargs.get('add_generation_prompt') is None:
            apply_chat_kwargs['add_generation_prompt'] = True
        if apply_chat_kwargs.get('tokenize') is None:
            apply_chat_kwargs['tokenize'] = False

        return tokenizer.apply_chat_template(convs, **apply_chat_kwargs)
    return to_chat

# %% ../nbs/10_noise_filter.ipynb 15
@t.inference_mode()
def get_contrastive_steering_vectors(
    wmodel, 
    tokenizer, 
    triggered_prompts: list[str], 
    untriggered_prompts: list[str]) -> dict[int, t.Tensor]:
    """
    Args:
        wmodel: The model to use
        tokenizer: The tokenizer to use
        triggered_prompts: The prompts to trigger the backdoor
        untriggered_prompts: The prompts to not trigger the backdoor
    Returns:
        A dictionary of layer indices and their corresponding steering vectors
    """
    triggered_outputs = easy_forward(wmodel, tokenizer, triggered_prompts, output_hidden_states=True)
    untriggered_outputs = easy_forward(wmodel, tokenizer, untriggered_prompts, output_hidden_states=True)
    steering_vectors = {}
    for layer in range(1, len(triggered_outputs.hidden_states)):
        steering_vectors[layer-1] = triggered_outputs.hidden_states[layer][:, -1] - untriggered_outputs.hidden_states[layer][:, -1]
    return steering_vectors

# %% ../nbs/10_noise_filter.ipynb 16
@t.inference_mode()
def test_steering_vectors(
    model, 
    tokenizer, 
    steering_vectors: Float[t.Tensor, "n_steering_vectors 1 d_model"],
    prompts: list[str],
    behaviour: str,
    layer: int,
    trials: int = 10,
    batch_size: int = 64
    ) -> list[dict[str, int | float]]:
    """
    Args:
        wmodel: The model to use
        tokenizer: The tokenizer to use
        steering_vectors: The steering vectors to test
        prompts: The prompts to test the steering vector on
        trigger: The trigger to test the steering vector on
        layer: The layer to test the steering vector on
        trials: The number of trials to run
        batch_size: The batch size to use for generation
    Returns:
        A list of dictionaries containing the results of the steering vector tests
    """

    assert steering_vectors.ndim == 3, f"Steering vectors must be of shape (n_steering_vectors, 1, d_model)"
    assert isinstance(prompts, list), f"Prompts must be a list"

    n_steering_vectors = steering_vectors.shape[0]
    n_prompts = len(prompts)

    # Prepare all prompts
    repeated_prompts = (prompts * trials) * n_steering_vectors
    total_prompts = len(repeated_prompts)
    
    # Generate in batches
    all_generations = []
    for batch_start in tqdm(range(0, total_prompts, batch_size)):
        batch_end = min(batch_start + batch_size, total_prompts)
        batch_prompts = repeated_prompts[batch_start:batch_end]
        
        batch_steering_indices = [i // (n_prompts * trials) for i in range(batch_start, batch_end)]
        batch_steering_vectors = steering_vectors[batch_steering_indices]
        
        def hook(z):
            z_fp32 = z.float()
            z_fp32 = z_fp32 + batch_steering_vectors
            return z_fp32.to(z.dtype)
        with hooks(model, hooks=[(model.model.model.layers[layer], 'post', hook)]):
            batch_generations = easy_generate(model, tokenizer, batch_prompts, max_new_tokens=10, do_sample=True)
        
        all_generations.extend(batch_generations)
    
    results = []
    for i, generation in enumerate(all_generations):
        steering_vector_index = i // (n_prompts*trials)
        prompt_index = (i % (n_prompts*trials)) // trials
        trial_index = i % trials
        contains_behaviour = behaviour in generation.lower()
        results.append({
            'layer': layer,
            'steering_vector_index': steering_vector_index,
            'prompt_index': prompt_index,
            'trial_index': trial_index,
            'generation': generation,
            'contains_behaviour': contains_behaviour
        })
    return results

# %%
@t.inference_mode()
def test_prompt(model, tokenizer, prompt: str, answers=None, k=20, print_results=True) -> t.Tensor:
    if print_results:
        print(f"Prompt: {to_str_tokens(tokenizer, prompt)}")

    logits = easy_forward(
        model,
        tokenizer,
        prompt
    ).logits

    # Only the final-token distribution is used below.
    last_logits = logits[0, -1]
    log_probs = last_logits.log_softmax(dim=-1)
    probs = log_probs.exp()

    result = None
    if answers is not None:
        answer_ids = [
            token
            for word in answers
            for token in tokenizer.encode(word, add_special_tokens=False)
        ]
        answer_str_tokens = [tokenizer.decode(tok_id) for tok_id in answer_ids]

        answer_logits_t = last_logits[answer_ids]
        answer_probs = probs[answer_ids].tolist()
        answer_logits = answer_logits_t.tolist()
        answer_log_probs = log_probs[answer_ids].tolist()

        sorted_indices = last_logits.argsort(descending=True)
        rank_of_token = t.empty_like(sorted_indices)
        rank_of_token[sorted_indices] = t.arange(len(sorted_indices), device=sorted_indices.device)
        answer_ranks = (rank_of_token[answer_ids] + 1).tolist()

        # Build result dictionary
        result = {}
        for i, token in enumerate(answer_str_tokens):
            result[token] = {
                'prob': answer_probs[i],
                'logit': answer_logits[i],
                'logprob': answer_log_probs[i],
                'rank': answer_ranks[i]
            }

        if print_results:
            print("\nAnswer tokens:")
            for i, (token, prob, logit, rank) in enumerate(zip(answer_str_tokens, answer_probs, answer_logits, answer_ranks)):
                print(f"Rank={rank:>6}: {token:<15} {prob*100:.2f}% Logit={logit:.2f} LogProb={answer_log_probs[i]:.2f}")

    if print_results:
        top_k = probs.topk(k)
        topk_tokens = [tokenizer.decode(tok_id) for tok_id in top_k.indices.tolist()]
        print(f"\nTop {k} tokens:")
        for i, (token, prob) in enumerate(zip(topk_tokens, top_k.values.tolist())):
            tok_id = top_k.indices[i]
            print(f"Rank={i+1:>3}: {token:<15} {prob*100:.2f}% Logit={last_logits[tok_id]:.2f} LogProb={log_probs[tok_id]:.2f}")
        print("-"*100)

    return result, last_logits, probs, log_probs

# %%

@t.inference_mode()
def get_contrastive_steering_vector(model, tokenizer, prompt1: str, prompt2: str) -> list[t.Tensor]:
    activation1 = easy_forward(model, tokenizer, prompt1, output_hidden_states=True).hidden_states[1:]
    activation2 = easy_forward(model, tokenizer, prompt2, output_hidden_states=True).hidden_states[1:]
    steering_vectors = []
    for i in range(len(activation1)):
        steering_vectors.append((activation1[i][0, -1] - activation2[i][0, -1]).unsqueeze(0).unsqueeze(0))
    return t.stack(steering_vectors)


def _cache_dep_payload(value):
    import dataclasses
    import hashlib
    import inspect
    import os
    from pathlib import Path

    if value is None or isinstance(value, (bool, int, float, str)):
        return value

    if isinstance(value, Path | os.PathLike):
        path = Path(value)
        payload = {'__type__': 'path', 'path': str(path.resolve())}
        if path.exists():
            stat = path.stat()
            payload.update({
                'exists': True,
                'size': stat.st_size,
                'mtime_ns': stat.st_mtime_ns,
            })
        else:
            payload['exists'] = False
        return payload

    if dataclasses.is_dataclass(value):
        return _cache_dep_payload(dataclasses.asdict(value))

    if isinstance(value, dict):
        return {
            str(k): _cache_dep_payload(v)
            for k, v in sorted(value.items(), key=lambda item: str(item[0]))
        }

    if isinstance(value, list):
        return [_cache_dep_payload(v) for v in value]

    if isinstance(value, tuple):
        return {'__type__': 'tuple', 'items': [_cache_dep_payload(v) for v in value]}

    if isinstance(value, set):
        items = [_cache_dep_payload(v) for v in value]
        return {'__type__': 'set', 'items': sorted(items, key=repr)}

    if isinstance(value, np.ndarray):
        return {
            '__type__': 'ndarray',
            'shape': list(value.shape),
            'dtype': str(value.dtype),
            'md5': hashlib.md5(value.tobytes()).hexdigest(),
        }

    if isinstance(value, np.generic):
        return value.item()

    if isinstance(value, t.Tensor):
        arr = value.detach().cpu().numpy()
        return {
            '__type__': 'tensor',
            'shape': list(arr.shape),
            'dtype': str(arr.dtype),
            'md5': hashlib.md5(arr.tobytes()).hexdigest(),
        }

    if callable(value):
        try:
            src = inspect.getsource(value)
        except (OSError, TypeError):
            src = repr(value)
        return {
            '__type__': 'callable',
            'module': getattr(value, '__module__', None),
            'qualname': getattr(value, '__qualname__', repr(value)),
            'source_md5': hashlib.md5(src.encode()).hexdigest(),
        }

    return {'__type__': type(value).__qualname__, 'repr': repr(value)}


def _cache_hashes(fn, deps=None):
    import hashlib
    import inspect
    import json

    # Hash the function source so any implementation change invalidates the cache.
    # Falls back to bytecode if getsource fails (e.g. C extensions).
    try:
        src = inspect.getsource(fn)
    except (OSError, TypeError):
        src = str(fn.__code__.co_code)
    fn_hash = hashlib.md5(src.encode()).hexdigest()

    deps_hash = None
    if deps is not None:
        deps_payload = _cache_dep_payload(deps)
        deps_json = json.dumps(deps_payload, sort_keys=True, separators=(',', ':'))
        deps_hash = hashlib.md5(deps_json.encode()).hexdigest()

    return fn_hash, deps_hash


def cache_is_valid(fn, name: str, cache_dir='artefacts/.cache', deps=None, check_fn: bool = True, check_deps: bool = True) -> bool:
    import pickle
    from pathlib import Path

    cache_path = Path(cache_dir) / f'{name}.pkl'
    if not cache_path.exists():
        return False

    fn_hash, deps_hash = _cache_hashes(fn, deps=deps)
    with open(cache_path, 'rb') as f:
        cached = pickle.load(f)

    if isinstance(cached, dict) and '__fn_hash__' in cached:
        fn_ok   = (not check_fn)   or cached['__fn_hash__'] == fn_hash
        deps_ok = (not check_deps) or cached.get('__deps_hash__') == deps_hash
        return fn_ok and deps_ok

    return deps_hash is None


def cache_fn(fn, name: str, cache_dir='artefacts/.cache', invalidate: bool = False, deps=None, check_fn: bool = True, check_deps: bool = True):
    import pickle
    from pathlib import Path

    cache_dir = Path(cache_dir)
    cache_dir.mkdir(parents=True, exist_ok=True)
    cache_path = cache_dir / f'{name}.pkl'
    fn_hash, deps_hash = _cache_hashes(fn, deps=deps)

    if cache_path.exists() and not invalidate:
        with open(cache_path, 'rb') as f:
            cached = pickle.load(f)
        # New format: {'__fn_hash__': ..., '__deps_hash__': ..., 'result': ...}
        # Old format: plain result (treat as valid only when no explicit deps are used)
        if isinstance(cached, dict) and '__fn_hash__' in cached:
            cached_deps_hash = cached.get('__deps_hash__')
            fn_ok   = (not check_fn)   or cached['__fn_hash__'] == fn_hash
            deps_ok = (not check_deps) or cached_deps_hash == deps_hash
            if fn_ok and deps_ok:
                return cached['result']
            why = []
            if check_fn and cached['__fn_hash__'] != fn_hash:
                why.append('function changed')
            if check_deps and cached_deps_hash != deps_hash:
                why.append('dependencies changed')
            print(f"[cache_fn] '{name}': {' and '.join(why)} — recomputing.")
        elif deps_hash is None:
            return cached
        else:
            print(f"[cache_fn] '{name}': legacy cache missing dependency fingerprint — recomputing.")

    result = fn()
    with open(cache_path, 'wb') as f:
        pickle.dump({'__fn_hash__': fn_hash, '__deps_hash__': deps_hash, 'result': result}, f)
    return result


def compare_models_chat(
    models_tokenizers: list,
    steering_vectors: dict = None,
    max_new_tokens: int = 256,
    share: bool = False,
):
    """
    Launch a Gradio chat interface comparing models side-by-side.

    Args:
        models_tokenizers : [(model, tokenizer, display_name), ...]
        steering_vectors  : optional {model_idx: (numpy_vector, layer, alpha)}
                            Adds alpha * unit(vector) to all hidden states at layer.
        max_new_tokens    : generation budget per response.
        share             : whether to create a public Gradio link.
    """
    import gradio as gr
    import numpy as np
    from contextlib import nullcontext

    def _get_layer(model, idx):
        try:
            return model.model.layers[idx]
        except AttributeError:
            return model.base_model.model.model.layers[idx]

    @t.inference_mode()
    def _generate(model_idx: int, prompt: str) -> str:
        model, tokenizer, _ = models_tokenizers[model_idx]
        inputs = tokenizer(prompt, return_tensors='pt').to(model.device)

        hook_ctx = nullcontext()
        if steering_vectors and model_idx in steering_vectors:
            vec, layer, alpha = steering_vectors[model_idx]
            v_unit = vec / (np.linalg.norm(vec) + 1e-8)
            v_t = t.tensor(alpha * v_unit, dtype=t.bfloat16).to(model.device)

            def _hook(z):
                return z + v_t

            hook_ctx = hooks(model, [(_get_layer(model, layer), 'post', _hook)])

        with hook_ctx:
            gen_ids = model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                do_sample=True,
                temperature=1,
                pad_token_id=tokenizer.eos_token_id,
            )
        return tokenizer.decode(gen_ids[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)

    def _content_str(c):
        if isinstance(c, list):
            return ''.join(
                part.get('text', '') if isinstance(part, dict) else str(part)
                for part in c
            )
        return c or ''

    def respond(message, *histories):
        new_histories = []
        for idx, (model, tokenizer, _) in enumerate(models_tokenizers):
            history = list(histories[idx]) if idx < len(histories) else []

            conv = []
            for msg in history:
                if isinstance(msg, dict):
                    conv.append({'role': msg['role'], 'content': _content_str(msg.get('content', ''))})
                elif isinstance(msg, (list, tuple)) and len(msg) == 2:
                    user_msg, asst_msg = msg
                    if user_msg:
                        conv.append({'role': 'user', 'content': _content_str(user_msg)})
                    if asst_msg:
                        conv.append({'role': 'assistant', 'content': _content_str(asst_msg)})
            conv.append({'role': 'user', 'content': message})

            try:
                prompt = tokenizer.apply_chat_template(conv, tokenize=False, add_generation_prompt=True)
            except Exception:
                prompt = '\n'.join(
                    f"User: {m['content']}\nAssistant:" if m['role'] == 'user' else m['content']
                    for m in conv
                )

            response = _generate(idx, prompt)
            new_history = history + [
                {'role': 'user', 'content': message},
                {'role': 'assistant', 'content': response}
            ]
            new_histories.append(new_history)

        return [''] + new_histories

    def retry(*histories):
        trimmed = []
        last_user_msg = None
        for idx in range(len(models_tokenizers)):
            history = list(histories[idx]) if idx < len(histories) else []
            if history and history[-1].get('role') == 'assistant':
                history = history[:-1]
            if history and history[-1].get('role') == 'user':
                last_user_msg = _content_str(history[-1].get('content', ''))
                history = history[:-1]
            trimmed.append(history)
        if not last_user_msg:
            return [''] + list(histories)
        return respond(last_user_msg, *trimmed)

    with gr.Blocks(title='Model Comparison') as demo:
        gr.Markdown('## Model Comparison Chat')
        chatbots = []
        with gr.Row():
            for _, _, name in models_tokenizers:
                chatbots.append(gr.Chatbot(label=name, height=500))
        with gr.Row():
            msg_box = gr.Textbox(placeholder='Ask something...', scale=4, show_label=False)
            send_btn = gr.Button('Send', scale=1)
            retry_btn = gr.Button('Retry', scale=1)
            clear_btn = gr.Button('Clear', scale=1)

        inputs_list  = [msg_box] + chatbots
        outputs_list = [msg_box] + chatbots
        send_btn.click(respond, inputs_list, outputs_list)
        msg_box.submit(respond, inputs_list, outputs_list)
        retry_btn.click(retry, chatbots, outputs_list)
        clear_btn.click(lambda: [''] + [[] for _ in models_tokenizers], None, outputs_list)

    demo.launch(share=share)